import {beforeEach,expect,it,vi} from 'vitest';
const rpc=vi.hoisted(()=>vi.fn());
vi.mock('../supabase',()=>({supabase:{rpc}}));
import {recordPendingDamage,type PendingDamageRecord} from './pendingDamage';
const input=():PendingDamageRecord=>({attack:{id:'attack',state:'attack_rolled',attack_kind:'attack_roll',hit_result:'hit'} as PendingDamageRecord['attack'],rolls:[4],raw:6,final:6,expectedBuffs:[],components:{version:1,components:[{key:'base',source:'base',label:'Hit',expression:'1d6+2',damageType:'psychic',rolls:[4],dieKinds:['rolled'],modifier:2,rawTotal:6}]}});
const receipt=(r=input())=>({attack:{...r.attack,state:'damage_rolled',damage_rolls:r.rolls,damage_raw:r.raw,damage_final:r.final,damage_components:r.components},replayed:false});
beforeEach(()=>rpc.mockReset());
it('sends frozen attack state, typed dice and bonus snapshot together',async()=>{rpc.mockResolvedValue({data:receipt(),error:null});expect((await recordPendingDamage(input())).replayed).toBe(false);expect(rpc).toHaveBeenCalledWith('record_pending_damage',expect.objectContaining({p_expected:expect.objectContaining({state:'attack_rolled',hit_result:'hit',damage_group_id:null}),p_expected_buffs:[],p_raw:6,p_final:6}));});
it('retries a lost response with identical dice and returns the committed winner',async()=>{rpc.mockResolvedValueOnce({error:{message:'Connection lost'}}).mockResolvedValueOnce({data:{...receipt(),replayed:true}});await recordPendingDamage(input());expect(rpc).toHaveBeenCalledTimes(2);expect(rpc.mock.calls[0]).toEqual(rpc.mock.calls[1]);});
it('does not retry a rejected stale bonus snapshot',async()=>{rpc.mockResolvedValue({error:{code:'P0001',message:'Attacker bonuses changed'}});await expect(recordPendingDamage(input())).rejects.toThrow(/bonuses changed/);expect(rpc).toHaveBeenCalledTimes(1);});
it('rejects a mismatched successful receipt without claiming no write happened',async()=>{rpc.mockResolvedValue({data:{...receipt(),attack:{...receipt().attack,damage_final:7}}});await expect(recordPendingDamage(input())).rejects.toMatchObject({definitelyNotPaid:false});});
it('accepts another valid committed roll on replay instead of reporting local dice',async()=>{const r=input();r.rolls=[2];r.raw=r.final=4;r.components.components[0]={...r.components.components[0],rolls:[2],rawTotal:4};rpc.mockResolvedValue({data:{...receipt(r),replayed:true}});expect((await recordPendingDamage(input())).attack.damage_final).toBe(4);});
it.each([null,{attack:{...receipt().attack,id:'other'},replayed:true},{attack:{...receipt().attack,damage_rolls:[null]},replayed:true},{attack:{...receipt().attack,damage_components:{}},replayed:true}])('rejects corrupt or unrelated receipts',async data=>{rpc.mockResolvedValue({data});await expect(recordPendingDamage(input())).rejects.toMatchObject({definitelyNotPaid:false});});
it('invalid components never reach the server',async()=>{const r=input();r.components.components[0].rawTotal=30;await expect(recordPendingDamage(r)).rejects.toMatchObject({definitelyNotPaid:true});expect(rpc).not.toHaveBeenCalled();});

it('JSONB key reordering does not invalidate the committed receipt',async()=>{const r=receipt();r.attack.damage_components.components=r.attack.damage_components.components.map(c=>Object.fromEntries(Object.entries(c).reverse()) as typeof c);rpc.mockResolvedValue({data:r});expect((await recordPendingDamage(input())).replayed).toBe(false);});
