import { useState } from 'react';

interface RollLogEntry {
  id: string;
  created_at: string;
  character_name: string;
  label: string;
  expression: string;
  results: number[];
  total: number;
}

interface SessionLogExportProps {
  rolls: RollLogEntry[];
  campaignName: string;
  sessionDate?: string;
}

export default function SessionLogExport({ rolls, campaignName, sessionDate }: SessionLogExportProps) {
  const [exporting, setExporting] = useState(false);

  const date = sessionDate ?? new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

  function buildMarkdown(): string {
    const lines: string[] = [
      `# 🎲 Session Log — ${campaignName}`,
      `**Date:** ${date}  `,
      `**Total Rolls:** ${rolls.length}`,
      '',
      '---',
      '',
    ];

    // Group by character
    const byChar: Record<string, RollLogEntry[]> = {};
    for (const roll of rolls) {
      if (!byChar[roll.character_name]) byChar[roll.character_name] = [];
      byChar[roll.character_name].push(roll);
    }

    for (const [charName, charRolls] of Object.entries(byChar)) {
      lines.push(`## ${charName}`);
      lines.push('');
      const nat20s = charRolls.filter(r => r.results.some(x => x === 20));
      const nat1s = charRolls.filter(r => r.results.some(x => x === 1));
      if (nat20s.length > 0 || nat1s.length > 0) {
        lines.push(`> ⭐ **${nat20s.length}** Natural 20s · 💀 **${nat1s.length}** Natural 1s`);
        lines.push('');
      }
      for (const roll of charRolls) {
        const time = new Date(roll.created_at).toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' });
        const nat20 = roll.results.some(x => x === 20) ? ' ⭐' : '';
        const nat1 = roll.results.some(x => x === 1) ? ' 💀' : '';
        lines.push(`- \`${time}\` **${roll.label}** (${roll.expression}): **${roll.total}**${nat20}${nat1}`);
      }
      lines.push('');
    }

    // Summary
    lines.push('---');
    lines.push('');
    lines.push('## Session Summary');
    lines.push('');
    const allNat20 = rolls.filter(r => r.results.some(x => x === 20));
    const allNat1 = rolls.filter(r => r.results.some(x => x === 1));
    const avgRoll = rolls.length > 0 ? (rolls.reduce((s, r) => s + r.total, 0) / rolls.length).toFixed(1) : 'N/A';
    lines.push(`- **Total rolls:** ${rolls.length}`);
    lines.push(`- **Average total:** ${avgRoll}`);
    lines.push(`- **Natural 20s:** ${allNat20.length}`);
    lines.push(`- **Natural 1s:** ${allNat1.length}`);
    if (allNat20.length > 0) {
      lines.push(`- **Best roll:** ${allNat20[0].character_name} — ${allNat20[0].label}`);
    }
    lines.push('');
    lines.push('*Generated by DNDKeep*');

    return lines.join('\n');
  }

  function downloadMarkdown() {
    setExporting(true);
    const md = buildMarkdown();
    const blob = new Blob([md], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `session-log-${campaignName.replace(/\s+/g, '-').toLowerCase()}-${date.replace(/\s+/g, '-')}.md`;
    a.click();
    URL.revokeObjectURL(url);
    setTimeout(() => setExporting(false), 1000);
  }

  function printLog() {
    const md = buildMarkdown();
    const win = window.open('', '_blank');
    if (!win) return;
    win.document.write(`
      <html>
      <head>
        <title>Session Log — ${campaignName}</title>
        <style>
          body { font-family: Georgia, serif; max-width: 800px; margin: 40px auto; color: #1a1a2e; line-height: 1.6; }
          h1 { color: #c9922a; border-bottom: 2px solid #c9922a; padding-bottom: 8px; }
          h2 { color: #4a3060; margin-top: 32px; }
          code { background: #f0f0f0; padding: 2px 4px; border-radius: 3px; font-size: 0.9em; }
          blockquote { border-left: 3px solid #c9922a; margin-left: 0; padding-left: 16px; color: #666; }
          hr { border: none; border-top: 1px solid #ddd; margin: 24px 0; }
          @media print { body { margin: 20px; } }
        </style>
      </head>
      <body>
        <pre style="white-space:pre-wrap;font-family:inherit">${md.replace(/</g,'&lt;').replace(/>/g,'&gt;')}</pre>
      </body>
      </html>
    `);
    win.print();
  }

  if (rolls.length === 0) {
    return (
      <div style={{ textAlign: 'center', padding: 'var(--sp-8)', color: 'var(--t-2)' }}>
        <div style={{ fontSize: 40, marginBottom: 'var(--sp-3)' }}>📋</div>
        <div style={{ fontFamily: 'var(--ff-body)', fontSize: 'var(--fs-sm)' }}>
          No rolls logged this session yet.
        </div>
      </div>
    );
  }

  // Quick stats
  const nat20Count = rolls.filter(r => r.results.some(x => x === 20)).length;
  const nat1Count = rolls.filter(r => r.results.some(x => x === 1)).length;
  const avgTotal = (rolls.reduce((s, r) => s + r.total, 0) / rolls.length).toFixed(1);

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--sp-4)' }}>
      {/* Stats summary */}
      <div style={{ display: 'flex', gap: 'var(--sp-4)', flexWrap: 'wrap', padding: 'var(--sp-3) var(--sp-4)', background: '#080d14', border: '1px solid var(--c-border)', borderRadius: 'var(--r-xl)' }}>
        {[
          { label: 'Total Rolls', value: rolls.length, color: 'var(--t-1)' },
          { label: 'Avg Total', value: avgTotal, color: '#60a5fa' },
          { label: '⭐ Nat 20s', value: nat20Count, color: 'var(--c-gold-l)' },
          { label: '💀 Nat 1s', value: nat1Count, color: '#f87171' },
        ].map(stat => (
          <div key={stat.label} style={{ display: 'flex', flexDirection: 'column', gap: 2 }}>
            <div style={{ fontFamily: 'var(--ff-body)', fontSize: 9, fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.1em', color: 'var(--t-2)' }}>{stat.label}</div>
            <div style={{ fontFamily: 'var(--ff-body)', fontWeight: 900, fontSize: 'var(--fs-xl)', color: stat.color, lineHeight: 1 }}>{stat.value}</div>
          </div>
        ))}
      </div>

      {/* Export buttons */}
      <div style={{ display: 'flex', gap: 'var(--sp-3)' }}>
        <button
          className="btn-gold btn-sm"
          onClick={downloadMarkdown}
          disabled={exporting}
        >
          📥 {exporting ? 'Exporting…' : 'Download Markdown'}
        </button>
        <button
          className="btn-secondary btn-sm"
          onClick={printLog}
        >
          🖨️ Print / Save PDF
        </button>
      </div>

      {/* Recent rolls preview */}
      <div>
        <div className="section-header">Recent Rolls (last 20)</div>
        <div style={{ display: 'flex', flexDirection: 'column', gap: 4 }}>
          {rolls.slice(0, 20).map(roll => {
            const nat20 = roll.results.some(x => x === 20);
            const nat1 = roll.results.some(x => x === 1);
            return (
              <div key={roll.id} style={{
                display: 'flex', alignItems: 'center', gap: 'var(--sp-3)',
                padding: '6px var(--sp-3)',
                border: nat20 ? '1px solid rgba(212,160,23,0.3)' : nat1 ? '1px solid rgba(248,113,113,0.3)' : '1px solid var(--c-border)',
                borderRadius: 'var(--r-md)',
                background: nat20 ? 'rgba(212,160,23,0.05)' : nat1 ? 'rgba(248,113,113,0.05)' : '#080d14',
              }}>
                <span style={{ fontFamily: 'var(--ff-body)', fontSize: 'var(--fs-xs)', color: 'var(--t-2)', minWidth: 48 }}>
                  {new Date(roll.created_at).toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' })}
                </span>
                <span style={{ fontFamily: 'var(--ff-body)', fontSize: 'var(--fs-xs)', color: 'var(--t-2)', minWidth: 80, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
                  {roll.character_name}
                </span>
                <span style={{ fontFamily: 'var(--ff-body)', fontSize: 'var(--fs-sm)', color: 'var(--t-2)', flex: 1 }}>
                  {roll.label}
                </span>
                <span style={{ fontFamily: 'var(--ff-body)', fontSize: 'var(--fs-xs)', color: 'var(--t-2)' }}>
                  {roll.expression}
                </span>
                <span style={{ fontFamily: 'var(--ff-body)', fontWeight: 700, fontSize: 'var(--fs-md)', color: nat20 ? 'var(--c-gold-l)' : nat1 ? '#f87171' : 'var(--t-1)', minWidth: 32, textAlign: 'right' }}>
                  {roll.total}{nat20 ? '⭐' : nat1 ? '💀' : ''}
                </span>
              </div>
            );
          })}
        </div>
      </div>
    </div>
  );
}
