// =============================================================
// DNDKeep — Core TypeScript Types
// 2024 PHB ruleset: backgrounds grant ASI, species do not.
// =============================================================

// --- Primitives & Unions ---

export type SubscriptionTier = 'free' | 'pro';

export type AbilityKey =
  | 'strength' | 'dexterity' | 'constitution'
  | 'intelligence' | 'wisdom' | 'charisma';

export type Alignment =
  | 'Lawful Good' | 'Neutral Good' | 'Chaotic Good'
  | 'Lawful Neutral' | 'True Neutral' | 'Chaotic Neutral'
  | 'Lawful Evil' | 'Neutral Evil' | 'Chaotic Evil'
  | 'Unaligned';

export type DiceType = 'd4' | 'd6' | 'd8' | 'd10' | 'd12' | 'd20' | 'd100';

export type SpellSchool =
  | 'Abjuration' | 'Conjuration' | 'Divination' | 'Enchantment'
  | 'Evocation' | 'Illusion' | 'Necromancy' | 'Transmutation';

export type SpellLevel = 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9;

export type MonsterType =
  | 'Aberration' | 'Beast' | 'Celestial' | 'Construct' | 'Dragon'
  | 'Elemental' | 'Fey' | 'Fiend' | 'Giant' | 'Humanoid'
  | 'Monstrosity' | 'Ooze' | 'Plant' | 'Undead';

export type CreatureSize = 'Tiny' | 'Small' | 'Medium' | 'Large' | 'Huge' | 'Gargantuan';

export type AbilityScoreMethod = 'standard_array' | 'point_buy' | 'manual' | 'dice_roll';

export type CampaignRole = 'dm' | 'player';

export type ConditionName =
  | 'Blinded' | 'Charmed' | 'Deafened' | 'Exhaustion' | 'Frightened'
  | 'Grappled' | 'Incapacitated' | 'Invisible' | 'Paralyzed' | 'Petrified'
  | 'Poisoned' | 'Prone' | 'Restrained' | 'Stunned' | 'Unconscious';

export type ClassName =
  | 'Fighter' | 'Wizard' | 'Rogue' | 'Cleric' | 'Barbarian'
  | 'Paladin' | 'Druid' | 'Ranger' | 'Warlock' | 'Monk'
  | 'Sorcerer' | 'Bard';

export type SpeciesName =
  | 'Human' | 'Elf' | 'Dwarf' | 'Halfling' | 'Gnome'
  | 'Half-Elf' | 'Tiefling' | 'Dragonborn' | 'Half-Orc' | 'Aasimar' | 'Orc';

// --- User & Auth ---

export interface Profile {
  id: string;
  email: string;
  display_name: string | null;
  subscription_tier: SubscriptionTier;
  stripe_customer_id: string | null;
  stripe_subscription_id: string | null;
  subscription_status: string;
  created_at: string;
  updated_at: string;
}

// --- Character ---

export interface Currency {
  cp: number;
  sp: number;
  ep: number;
  gp: number;
  pp: number;
}

export interface InventoryItem {
  id: string;
  name: string;
  quantity: number;
  weight: number;
  description: string;
  equipped: boolean;
  magical: boolean;
}

/** Per-slot-level data: how many total, how many already used */
export interface SpellSlotLevel {
  total: number;
  used: number;
}

/** Key is the spell slot level (1–9) as a string */
export type SpellSlots = Record<string, SpellSlotLevel>;

export interface ASIRecord {
  ability: AbilityKey;
  amount: number;
  source: 'background' | 'feat' | 'level';
}

export interface Character {
  id: string;
  user_id: string;
  campaign_id: string | null;

  // Identity
  name: string;
  species: string;
  class_name: string;
  subclass: string | null;
  background: string;
  level: number;
  experience_points: number;
  alignment: Alignment | null;
  avatar_url: string | null;
  inspiration: boolean;
  equipped_armor: string;

  // Raw ability scores (modifiers computed client-side via gameUtils)
  strength: number;
  dexterity: number;
  constitution: number;
  intelligence: number;
  wisdom: number;
  charisma: number;

  // HP
  max_hp: number;
  current_hp: number;
  temp_hp: number;
  hit_dice_spent: number;  // number spent since last long rest; max = level

  // Combat
  armor_class: number;
  speed: number;
  initiative_bonus: number;

  // Proficiencies (stored as arrays of canonical names)
  saving_throw_proficiencies: AbilityKey[];
  skill_proficiencies: string[];
  skill_expertises: string[];

  // Spellcasting
  spell_slots: SpellSlots;
  prepared_spells: string[];  // spell ids
  known_spells: string[];     // spell ids

  // Inventory
  inventory: InventoryItem[];
  currency: Currency;

  // Conditions
  active_conditions: ConditionName[];

  // Death saves (only relevant when current_hp === 0)
  death_saves_successes: number;  // 0–3; three successes stabilizes the character
  death_saves_failures: number;   // 0–3; three failures = dead

  // Narrative
  notes: string;
  personality_traits: string;
  ideals: string;
  bonds: string;
  flaws: string;
  features_and_traits: string;

  // Creation meta
  ability_score_improvements: ASIRecord[];
  ability_score_method: AbilityScoreMethod;

  created_at: string;
  updated_at: string;
}

/** Computed/derived stats — not persisted, generated by gameUtils */
export interface ComputedStats {
  proficiency_bonus: number;
  modifiers: Record<AbilityKey, number>;
  saving_throws: Record<AbilityKey, { total: number; proficient: boolean }>;
  skills: Record<string, { total: number; proficient: boolean; expert: boolean }>;
  passive_perception: number;
  initiative: number;
  spell_save_dc: number | null;
  spell_attack_bonus: number | null;
}

// --- D&D Data Shapes ---

export interface SpeciesTrait {
  name: string;
  description: string;
}

export interface SpeciesData {
  name: SpeciesName;
  size: CreatureSize;
  speed: number;
  // 2024 PHB: no fixed ASIs — species are trait-only
  traits: SpeciesTrait[];
  languages: string[];
  darkvision: number;  // 0 if none, otherwise feet
}

export interface BackgroundData {
  name: string;
  // 2024 PHB: each background grants exactly +2 and +1 to specific abilities
  asi_primary: AbilityKey;    // +2
  asi_secondary: AbilityKey;  // +1
  skill_proficiencies: [string, string];
  tool_proficiency: string | null;
  languages: number;  // number of additional languages granted
  feature_name: string;
  feature_description: string;
  starting_equipment: string[];
}

export interface SubclassData {
  name: string;
  description: string;
  unlock_level: number;
}

export interface ClassData {
  name: ClassName;
  hit_die: number;
  primary_abilities: AbilityKey[];
  saving_throw_proficiencies: AbilityKey[];
  skill_choices: string[];
  skill_count: number;
  armor_proficiencies: string[];
  weapon_proficiencies: string[];
  tool_proficiencies: string[];
  is_spellcaster: boolean;
  spellcasting_ability: AbilityKey | null;
  spellcaster_type: 'full' | 'half' | 'warlock' | 'none';
  subclasses: SubclassData[];
}

export interface SpellData {
  id: string;          // kebab-case slug
  name: string;
  level: SpellLevel;
  school: SpellSchool;
  casting_time: string;
  range: string;
  components: string;  // e.g. "V, S, M (a tiny ball of bat guano)"
  duration: string;
  concentration: boolean;
  ritual: boolean;
  classes: string[];
  description: string;
  higher_levels?: string;
}

export interface MonsterData {
  id: string;
  name: string;
  type: MonsterType;
  cr: number | string;  // "1/8" | "1/4" | "1/2" | 1 | 2 ...
  size: CreatureSize;
  hp: number;
  hp_formula: string;
  ac: number;
  ac_note: string;
  speed: number;
  str: number; dex: number; con: number;
  int: number; wis: number; cha: number;
  attack_name: string;
  attack_bonus: number;
  attack_damage: string;  // e.g. "2d6 + 4"
  xp: number;
}

export interface ConditionData {
  name: ConditionName;
  description: string;
  effects: string[];
}

export interface SkillData {
  name: string;
  ability: AbilityKey;
}

// --- Campaign ---

export interface Campaign {
  id: string;
  owner_id: string;
  name: string;
  description: string;
  setting: string;
  is_active: boolean;
  join_code: string;
  created_at: string;
  updated_at: string;
}

export interface CampaignMember {
  id: string;
  campaign_id: string;
  user_id: string;
  role: CampaignRole;
  joined_at: string;
}

// --- Combat ---

export interface Combatant {
  id: string;
  name: string;
  initiative: number;
  current_hp: number;
  max_hp: number;
  ac: number;
  is_monster: boolean;
  monster_id?: string;
  character_id?: string;
  conditions: ConditionName[];
}

export interface SessionState {
  id: string;
  campaign_id: string;
  initiative_order: Combatant[];
  current_turn: number;
  round: number;
  combat_active: boolean;
  updated_at: string;
}

// --- Dice ---

export interface DiceEntry {
  id: string;
  count: number;
  die: DiceType;
  label: string;
  modifier: number;
}

export interface RollResult {
  id: string;
  label: string;
  dice_expression: string;
  individual_results: number[];
  modifier: number;
  total: number;
  character_name?: string;
  rolled_at: string;
}

// --- Notes ---

export type NoteField =
  | 'notes'
  | 'personality_traits'
  | 'ideals'
  | 'bonds'
  | 'flaws'
  | 'features_and_traits';

// --- Spell Slot Table ---
// Indexed by class level (1–20), value is array of slots per level [1st...9th]
export type SpellSlotRow = number[];
export type SpellSlotTable = Record<number, SpellSlotRow>;
