// Auto-generated from Supabase schema introspection at v2.250.0.
// Do NOT hand-edit. Regenerate via the live schema introspection
// query in `information_schema.columns` for project
// `ufowdrspkprlpdnjjkaj`, then re-run /home/claude/gen/gen.py.
//
// Shape is compatible with `supabase gen types typescript` so a
// future CLI-driven regeneration drops in cleanly.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      action_log_reactions: {
        Row: {
          id: string;
          log_id: string | null;
          user_id: string | null;
          character_name: string;
          emoji: string;
          created_at: string | null;
        };
        Insert: {
          id?: string;
          log_id?: string | null;
          user_id?: string | null;
          character_name?: string;
          emoji: string;
          created_at?: string | null;
        };
        Update: {
          id?: string;
          log_id?: string | null;
          user_id?: string | null;
          character_name?: string;
          emoji?: string;
          created_at?: string | null;
        };
        Relationships: [];
      };
      action_logs: {
        Row: {
          id: string;
          campaign_id: string | null;
          character_id: string | null;
          character_name: string;
          action_type: string;
          action_name: string;
          target_name: string | null;
          dice_expression: string | null;
          individual_results: number[] | null;
          total: number | null;
          hit_result: string | null;
          notes: string | null;
          created_at: string | null;
        };
        Insert: {
          id?: string;
          campaign_id?: string | null;
          character_id?: string | null;
          character_name?: string;
          action_type?: string;
          action_name?: string;
          target_name?: string | null;
          dice_expression?: string | null;
          individual_results?: number[] | null;
          total?: number | null;
          hit_result?: string | null;
          notes?: string | null;
          created_at?: string | null;
        };
        Update: {
          id?: string;
          campaign_id?: string | null;
          character_id?: string | null;
          character_name?: string;
          action_type?: string;
          action_name?: string;
          target_name?: string | null;
          dice_expression?: string | null;
          individual_results?: number[] | null;
          total?: number | null;
          hit_result?: string | null;
          notes?: string | null;
          created_at?: string | null;
        };
        Relationships: [];
      };
      battle_maps: {
        Row: {
          id: string;
          campaign_id: string | null;
          name: string | null;
          image_url: string;
          width: number | null;
          height: number | null;
          tokens: Json | null;
          notes: string | null;
          active: boolean | null;
          created_at: string | null;
          grid_size: number;
          grid_cols: number;
          grid_rows: number;
          map_active_for_players: boolean;
          background_color: string;
          drawings: Json;
          updated_at: string;
          version: number;
          walls: Json;
        };
        Insert: {
          id?: string;
          campaign_id?: string | null;
          name?: string | null;
          image_url: string;
          width?: number | null;
          height?: number | null;
          tokens?: Json | null;
          notes?: string | null;
          active?: boolean | null;
          created_at?: string | null;
          grid_size?: number;
          grid_cols?: number;
          grid_rows?: number;
          map_active_for_players?: boolean;
          background_color?: string;
          drawings?: Json;
          updated_at?: string;
          version?: number;
          walls?: Json;
        };
        Update: {
          id?: string;
          campaign_id?: string | null;
          name?: string | null;
          image_url?: string;
          width?: number | null;
          height?: number | null;
          tokens?: Json | null;
          notes?: string | null;
          active?: boolean | null;
          created_at?: string | null;
          grid_size?: number;
          grid_cols?: number;
          grid_rows?: number;
          map_active_for_players?: boolean;
          background_color?: string;
          drawings?: Json;
          updated_at?: string;
          version?: number;
          walls?: Json;
        };
        Relationships: [];
      };
      campaign_chat: {
        Row: {
          id: string;
          campaign_id: string | null;
          user_id: string | null;
          character_name: string;
          avatar_url: string | null;
          message: string;
          message_type: string | null;
          created_at: string | null;
          roll_total: number | null;
          roll_label: string | null;
        };
        Insert: {
          id?: string;
          campaign_id?: string | null;
          user_id?: string | null;
          character_name?: string;
          avatar_url?: string | null;
          message: string;
          message_type?: string | null;
          created_at?: string | null;
          roll_total?: number | null;
          roll_label?: string | null;
        };
        Update: {
          id?: string;
          campaign_id?: string | null;
          user_id?: string | null;
          character_name?: string;
          avatar_url?: string | null;
          message?: string;
          message_type?: string | null;
          created_at?: string | null;
          roll_total?: number | null;
          roll_label?: string | null;
        };
        Relationships: [];
      };
      campaign_members: {
        Row: {
          id: string;
          campaign_id: string;
          user_id: string;
          role: string;
          joined_at: string;
        };
        Insert: {
          id?: string;
          campaign_id: string;
          user_id: string;
          role?: string;
          joined_at?: string;
        };
        Update: {
          id?: string;
          campaign_id?: string;
          user_id?: string;
          role?: string;
          joined_at?: string;
        };
        Relationships: [];
      };
      campaigns: {
        Row: {
          id: string;
          owner_id: string;
          name: string;
          description: string;
          setting: string;
          is_active: boolean;
          created_at: string;
          updated_at: string;
          join_code: string;
          notes: string | null;
          hp_visibility_mode: string;
          automation_settings: Json;
          automation_defaults: Json;
          combat_automation_settings: Json;
          encumbrance_variant: string;
          default_ruleset_version: string | null;
          award_xp_enabled: boolean;
        };
        Insert: {
          id?: string;
          owner_id: string;
          name: string;
          description?: string;
          setting?: string;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
          join_code: string;
          notes?: string | null;
          hp_visibility_mode?: string;
          automation_settings?: Json;
          automation_defaults?: Json;
          combat_automation_settings?: Json;
          encumbrance_variant?: string;
          default_ruleset_version?: string | null;
          award_xp_enabled?: boolean;
        };
        Update: {
          id?: string;
          owner_id?: string;
          name?: string;
          description?: string;
          setting?: string;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
          join_code?: string;
          notes?: string | null;
          hp_visibility_mode?: string;
          automation_settings?: Json;
          automation_defaults?: Json;
          combat_automation_settings?: Json;
          encumbrance_variant?: string;
          default_ruleset_version?: string | null;
          award_xp_enabled?: boolean;
        };
        Relationships: [];
      };
      character_history: {
        Row: {
          id: string;
          character_id: string;
          user_id: string;
          event_type: string;
          field: string | null;
          old_value: Json | null;
          new_value: Json | null;
          description: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          character_id: string;
          user_id: string;
          event_type: string;
          field?: string | null;
          old_value?: Json | null;
          new_value?: Json | null;
          description: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          character_id?: string;
          user_id?: string;
          event_type?: string;
          field?: string | null;
          old_value?: Json | null;
          new_value?: Json | null;
          description?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      characters: {
        Row: {
          id: string;
          user_id: string;
          campaign_id: string | null;
          name: string;
          species: string;
          class_name: string;
          subclass: string | null;
          background: string;
          level: number;
          experience_points: number;
          alignment: string | null;
          avatar_url: string | null;
          strength: number;
          dexterity: number;
          constitution: number;
          intelligence: number;
          wisdom: number;
          charisma: number;
          max_hp: number;
          current_hp: number;
          temp_hp: number;
          hit_dice_spent: number;
          armor_class: number;
          speed: number;
          initiative_bonus: number;
          saving_throw_proficiencies: string[];
          skill_proficiencies: string[];
          skill_expertises: string[];
          spell_slots: Json;
          prepared_spells: string[];
          known_spells: string[];
          inventory: Json;
          currency: Json;
          active_conditions: string[];
          death_saves_successes: number;
          death_saves_failures: number;
          notes: string;
          personality_traits: string;
          ideals: string;
          bonds: string;
          flaws: string;
          features_and_traits: string;
          ability_score_improvements: Json;
          ability_score_method: string;
          created_at: string;
          updated_at: string;
          inspiration: boolean | null;
          equipped_armor: string | null;
          push_subscription: Json | null;
          share_token: string | null;
          share_enabled: boolean | null;
          weapons: Json | null;
          wildshape_active: boolean | null;
          wildshape_beast_name: string | null;
          wildshape_current_hp: number | null;
          wildshape_max_hp: number | null;
          concentration_spell: string | null;
          class_resources: Json | null;
          secondary_class: string | null;
          secondary_level: number | null;
          secondary_subclass: string | null;
          features_text: string | null;
          active_buffs: Json | null;
          gained_feats: string[] | null;
          feature_uses: Json | null;
          automation_overrides: Json;
          advanced_automations_unlocked: boolean;
          advanced_edits_unlocked: boolean;
          advanced_spell_edits_unlocked: boolean;
          exhaustion_level: number;
          extra_languages: string[];
          extra_tool_proficiencies: string[];
          pending_manual_level_grants: number;
          advanced_deep_edits_unlocked: boolean;
          concentration_rounds_remaining: number | null;
          damage_resistances: string[];
          damage_immunities: string[];
          damage_vulnerabilities: string[];
          nat_1_20_saves: boolean;
          long_rest_clears_combat_conditions: boolean;
          species_choices: Json | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          campaign_id?: string | null;
          name: string;
          species: string;
          class_name: string;
          subclass?: string | null;
          background: string;
          level?: number;
          experience_points?: number;
          alignment?: string | null;
          avatar_url?: string | null;
          strength?: number;
          dexterity?: number;
          constitution?: number;
          intelligence?: number;
          wisdom?: number;
          charisma?: number;
          max_hp?: number;
          current_hp?: number;
          temp_hp?: number;
          hit_dice_spent?: number;
          armor_class?: number;
          speed?: number;
          initiative_bonus?: number;
          saving_throw_proficiencies?: string[];
          skill_proficiencies?: string[];
          skill_expertises?: string[];
          spell_slots?: Json;
          prepared_spells?: string[];
          known_spells?: string[];
          inventory?: Json;
          currency?: Json;
          active_conditions?: string[];
          death_saves_successes?: number;
          death_saves_failures?: number;
          notes?: string;
          personality_traits?: string;
          ideals?: string;
          bonds?: string;
          flaws?: string;
          features_and_traits?: string;
          ability_score_improvements?: Json;
          ability_score_method?: string;
          created_at?: string;
          updated_at?: string;
          inspiration?: boolean | null;
          equipped_armor?: string | null;
          push_subscription?: Json | null;
          share_token?: string | null;
          share_enabled?: boolean | null;
          weapons?: Json | null;
          wildshape_active?: boolean | null;
          wildshape_beast_name?: string | null;
          wildshape_current_hp?: number | null;
          wildshape_max_hp?: number | null;
          concentration_spell?: string | null;
          class_resources?: Json | null;
          secondary_class?: string | null;
          secondary_level?: number | null;
          secondary_subclass?: string | null;
          features_text?: string | null;
          active_buffs?: Json | null;
          gained_feats?: string[] | null;
          feature_uses?: Json | null;
          automation_overrides?: Json;
          advanced_automations_unlocked?: boolean;
          advanced_edits_unlocked?: boolean;
          advanced_spell_edits_unlocked?: boolean;
          exhaustion_level?: number;
          extra_languages?: string[];
          extra_tool_proficiencies?: string[];
          pending_manual_level_grants?: number;
          advanced_deep_edits_unlocked?: boolean;
          concentration_rounds_remaining?: number | null;
          damage_resistances?: string[];
          damage_immunities?: string[];
          damage_vulnerabilities?: string[];
          nat_1_20_saves?: boolean;
          long_rest_clears_combat_conditions?: boolean;
          species_choices?: Json | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          campaign_id?: string | null;
          name?: string;
          species?: string;
          class_name?: string;
          subclass?: string | null;
          background?: string;
          level?: number;
          experience_points?: number;
          alignment?: string | null;
          avatar_url?: string | null;
          strength?: number;
          dexterity?: number;
          constitution?: number;
          intelligence?: number;
          wisdom?: number;
          charisma?: number;
          max_hp?: number;
          current_hp?: number;
          temp_hp?: number;
          hit_dice_spent?: number;
          armor_class?: number;
          speed?: number;
          initiative_bonus?: number;
          saving_throw_proficiencies?: string[];
          skill_proficiencies?: string[];
          skill_expertises?: string[];
          spell_slots?: Json;
          prepared_spells?: string[];
          known_spells?: string[];
          inventory?: Json;
          currency?: Json;
          active_conditions?: string[];
          death_saves_successes?: number;
          death_saves_failures?: number;
          notes?: string;
          personality_traits?: string;
          ideals?: string;
          bonds?: string;
          flaws?: string;
          features_and_traits?: string;
          ability_score_improvements?: Json;
          ability_score_method?: string;
          created_at?: string;
          updated_at?: string;
          inspiration?: boolean | null;
          equipped_armor?: string | null;
          push_subscription?: Json | null;
          share_token?: string | null;
          share_enabled?: boolean | null;
          weapons?: Json | null;
          wildshape_active?: boolean | null;
          wildshape_beast_name?: string | null;
          wildshape_current_hp?: number | null;
          wildshape_max_hp?: number | null;
          concentration_spell?: string | null;
          class_resources?: Json | null;
          secondary_class?: string | null;
          secondary_level?: number | null;
          secondary_subclass?: string | null;
          features_text?: string | null;
          active_buffs?: Json | null;
          gained_feats?: string[] | null;
          feature_uses?: Json | null;
          automation_overrides?: Json;
          advanced_automations_unlocked?: boolean;
          advanced_edits_unlocked?: boolean;
          advanced_spell_edits_unlocked?: boolean;
          exhaustion_level?: number;
          extra_languages?: string[];
          extra_tool_proficiencies?: string[];
          pending_manual_level_grants?: number;
          advanced_deep_edits_unlocked?: boolean;
          concentration_rounds_remaining?: number | null;
          damage_resistances?: string[];
          damage_immunities?: string[];
          damage_vulnerabilities?: string[];
          nat_1_20_saves?: boolean;
          long_rest_clears_combat_conditions?: boolean;
          species_choices?: Json | null;
        };
        Relationships: [];
      };
      combat_encounters: {
        Row: {
          id: string;
          campaign_id: string;
          name: string | null;
          status: string;
          round_number: number;
          current_turn_index: number;
          initiative_mode: string;
          hidden_monster_reveal_mode: string;
          started_at: string | null;
          ended_at: string | null;
          created_at: string;
          updated_at: string;
          in_lair: boolean;
          lair_actions_config: Json;
          lair_action_used_this_round: boolean;
        };
        Insert: {
          id?: string;
          campaign_id: string;
          name?: string | null;
          status?: string;
          round_number?: number;
          current_turn_index?: number;
          initiative_mode?: string;
          hidden_monster_reveal_mode?: string;
          started_at?: string | null;
          ended_at?: string | null;
          created_at?: string;
          updated_at?: string;
          in_lair?: boolean;
          lair_actions_config?: Json;
          lair_action_used_this_round?: boolean;
        };
        Update: {
          id?: string;
          campaign_id?: string;
          name?: string | null;
          status?: string;
          round_number?: number;
          current_turn_index?: number;
          initiative_mode?: string;
          hidden_monster_reveal_mode?: string;
          started_at?: string | null;
          ended_at?: string | null;
          created_at?: string;
          updated_at?: string;
          in_lair?: boolean;
          lair_actions_config?: Json;
          lair_action_used_this_round?: boolean;
        };
        Relationships: [];
      };
      combat_events: {
        Row: {
          id: string;
          campaign_id: string | null;
          encounter_id: string | null;
          chain_id: string;
          sequence: number;
          parent_event_id: string | null;
          actor_type: string;
          actor_id: string | null;
          actor_name: string;
          target_type: string | null;
          target_id: string | null;
          target_name: string | null;
          event_type: string;
          payload: Json;
          visibility: string;
          legacy_source: string | null;
          legacy_id: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          campaign_id?: string | null;
          encounter_id?: string | null;
          chain_id: string;
          sequence?: number;
          parent_event_id?: string | null;
          actor_type: string;
          actor_id?: string | null;
          actor_name: string;
          target_type?: string | null;
          target_id?: string | null;
          target_name?: string | null;
          event_type: string;
          payload?: Json;
          visibility?: string;
          legacy_source?: string | null;
          legacy_id?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          campaign_id?: string | null;
          encounter_id?: string | null;
          chain_id?: string;
          sequence?: number;
          parent_event_id?: string | null;
          actor_type?: string;
          actor_id?: string | null;
          actor_name?: string;
          target_type?: string | null;
          target_id?: string | null;
          target_name?: string | null;
          event_type?: string;
          payload?: Json;
          visibility?: string;
          legacy_source?: string | null;
          legacy_id?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      combat_participants: {
        Row: {
          id: string;
          encounter_id: string;
          campaign_id: string;
          participant_type: string;
          entity_id: string;
          name: string;
          initiative: number | null;
          initiative_tiebreaker: number | null;
          turn_order: number;
          action_used: boolean;
          bonus_used: boolean;
          reaction_used: boolean;
          movement_used_ft: number;
          leveled_spell_cast: boolean;
          hidden_from_players: boolean;
          current_hp: number | null;
          max_hp: number | null;
          temp_hp: number;
          ac: number | null;
          death_save_successes: number;
          death_save_failures: number;
          is_stable: boolean;
          is_dead: boolean;
          active_conditions: string[];
          concentration_spell_id: string | null;
          created_at: string;
          updated_at: string;
          persistent_cover: Json;
          max_speed_ft: number;
          dash_used_this_turn: boolean;
          disengaged_this_turn: boolean;
          condition_sources: Json;
          active_buffs: Json;
          exhaustion_level: number;
          legendary_actions_total: number;
          legendary_actions_remaining: number;
          legendary_actions_config: Json;
          legendary_resistance: number | null;
          legendary_resistance_used: number | null;
        };
        Insert: {
          id?: string;
          encounter_id: string;
          campaign_id: string;
          participant_type: string;
          entity_id: string;
          name: string;
          initiative?: number | null;
          initiative_tiebreaker?: number | null;
          turn_order?: number;
          action_used?: boolean;
          bonus_used?: boolean;
          reaction_used?: boolean;
          movement_used_ft?: number;
          leveled_spell_cast?: boolean;
          hidden_from_players?: boolean;
          current_hp?: number | null;
          max_hp?: number | null;
          temp_hp?: number;
          ac?: number | null;
          death_save_successes?: number;
          death_save_failures?: number;
          is_stable?: boolean;
          is_dead?: boolean;
          active_conditions?: string[];
          concentration_spell_id?: string | null;
          created_at?: string;
          updated_at?: string;
          persistent_cover?: Json;
          max_speed_ft?: number;
          dash_used_this_turn?: boolean;
          disengaged_this_turn?: boolean;
          condition_sources?: Json;
          active_buffs?: Json;
          exhaustion_level?: number;
          legendary_actions_total?: number;
          legendary_actions_remaining?: number;
          legendary_actions_config?: Json;
          legendary_resistance?: number | null;
          legendary_resistance_used?: number | null;
        };
        Update: {
          id?: string;
          encounter_id?: string;
          campaign_id?: string;
          participant_type?: string;
          entity_id?: string;
          name?: string;
          initiative?: number | null;
          initiative_tiebreaker?: number | null;
          turn_order?: number;
          action_used?: boolean;
          bonus_used?: boolean;
          reaction_used?: boolean;
          movement_used_ft?: number;
          leveled_spell_cast?: boolean;
          hidden_from_players?: boolean;
          current_hp?: number | null;
          max_hp?: number | null;
          temp_hp?: number;
          ac?: number | null;
          death_save_successes?: number;
          death_save_failures?: number;
          is_stable?: boolean;
          is_dead?: boolean;
          active_conditions?: string[];
          concentration_spell_id?: string | null;
          created_at?: string;
          updated_at?: string;
          persistent_cover?: Json;
          max_speed_ft?: number;
          dash_used_this_turn?: boolean;
          disengaged_this_turn?: boolean;
          condition_sources?: Json;
          active_buffs?: Json;
          exhaustion_level?: number;
          legendary_actions_total?: number;
          legendary_actions_remaining?: number;
          legendary_actions_config?: Json;
          legendary_resistance?: number | null;
          legendary_resistance_used?: number | null;
        };
        Relationships: [];
      };
      deploy_queue: {
        Row: {
          id: number;
          path: string;
          content: string;
          created_at: string | null;
        };
        Insert: {
          id?: number;
          path: string;
          content: string;
          created_at?: string | null;
        };
        Update: {
          id?: number;
          path?: string;
          content?: string;
          created_at?: string | null;
        };
        Relationships: [];
      };
      dice_skin_unlocks: {
        Row: {
          id: string;
          user_id: string;
          skin_id: string;
          unlocked_at: string | null;
          stripe_payment_intent: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          skin_id: string;
          unlocked_at?: string | null;
          stripe_payment_intent?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          skin_id?: string;
          unlocked_at?: string | null;
          stripe_payment_intent?: string | null;
        };
        Relationships: [];
      };
      discord_integrations: {
        Row: {
          id: string;
          campaign_id: string | null;
          guild_id: string;
          guild_name: string | null;
          channel_id: string | null;
          webhook_url: string | null;
          installed_by: string | null;
          active: boolean | null;
          created_at: string | null;
        };
        Insert: {
          id?: string;
          campaign_id?: string | null;
          guild_id: string;
          guild_name?: string | null;
          channel_id?: string | null;
          webhook_url?: string | null;
          installed_by?: string | null;
          active?: boolean | null;
          created_at?: string | null;
        };
        Update: {
          id?: string;
          campaign_id?: string | null;
          guild_id?: string;
          guild_name?: string | null;
          channel_id?: string | null;
          webhook_url?: string | null;
          installed_by?: string | null;
          active?: boolean | null;
          created_at?: string | null;
        };
        Relationships: [];
      };
      dm_npc_roster: {
        Row: {
          id: string;
          owner_id: string;
          campaign_id: string | null;
          name: string;
          type: string;
          cr: string;
          size: string;
          hp: number;
          max_hp: number;
          ac: number;
          speed: number;
          str: number;
          dex: number;
          con: number;
          int: number;
          wis: number;
          cha: number;
          attack_name: string;
          attack_bonus: number;
          attack_damage: string;
          xp: number;
          description: string;
          traits: string;
          immunities: string;
          image_url: string | null;
          emoji: string;
          color: string;
          source_monster_id: string | null;
          times_used: number;
          last_used_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          owner_id: string;
          campaign_id?: string | null;
          name: string;
          type?: string;
          cr?: string;
          size?: string;
          hp?: number;
          max_hp?: number;
          ac?: number;
          speed?: number;
          str?: number;
          dex?: number;
          con?: number;
          int?: number;
          wis?: number;
          cha?: number;
          attack_name?: string;
          attack_bonus?: number;
          attack_damage?: string;
          xp?: number;
          description?: string;
          traits?: string;
          immunities?: string;
          image_url?: string | null;
          emoji?: string;
          color?: string;
          source_monster_id?: string | null;
          times_used?: number;
          last_used_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          owner_id?: string;
          campaign_id?: string | null;
          name?: string;
          type?: string;
          cr?: string;
          size?: string;
          hp?: number;
          max_hp?: number;
          ac?: number;
          speed?: number;
          str?: number;
          dex?: number;
          con?: number;
          int?: number;
          wis?: number;
          cha?: number;
          attack_name?: string;
          attack_bonus?: number;
          attack_damage?: string;
          xp?: number;
          description?: string;
          traits?: string;
          immunities?: string;
          image_url?: string | null;
          emoji?: string;
          color?: string;
          source_monster_id?: string | null;
          times_used?: number;
          last_used_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      homebrew_classes: {
        Row: {
          id: string;
          user_id: string;
          created_at: string;
          updated_at: string;
          name: string;
          description: string;
          hit_die: number;
          primary_abilities: string[];
          saving_throw_proficiencies: string[];
          skill_choices: string[];
          skill_count: number;
          armor_proficiencies: string[];
          weapon_proficiencies: string[];
          tool_proficiencies: string[];
          is_spellcaster: boolean;
          spellcasting_ability: string | null;
          spellcaster_type: string;
          subclasses: Json;
          is_public: boolean;
        };
        Insert: {
          id?: string;
          user_id: string;
          created_at?: string;
          updated_at?: string;
          name: string;
          description?: string;
          hit_die?: number;
          primary_abilities?: string[];
          saving_throw_proficiencies?: string[];
          skill_choices?: string[];
          skill_count?: number;
          armor_proficiencies?: string[];
          weapon_proficiencies?: string[];
          tool_proficiencies?: string[];
          is_spellcaster?: boolean;
          spellcasting_ability?: string | null;
          spellcaster_type?: string;
          subclasses?: Json;
          is_public?: boolean;
        };
        Update: {
          id?: string;
          user_id?: string;
          created_at?: string;
          updated_at?: string;
          name?: string;
          description?: string;
          hit_die?: number;
          primary_abilities?: string[];
          saving_throw_proficiencies?: string[];
          skill_choices?: string[];
          skill_count?: number;
          armor_proficiencies?: string[];
          weapon_proficiencies?: string[];
          tool_proficiencies?: string[];
          is_spellcaster?: boolean;
          spellcasting_ability?: string | null;
          spellcaster_type?: string;
          subclasses?: Json;
          is_public?: boolean;
        };
        Relationships: [];
      };
      homebrew_items: {
        Row: {
          id: string;
          user_id: string | null;
          name: string;
          item_type: string | null;
          rarity: string | null;
          requires_attunement: boolean | null;
          description: string | null;
          weight: number | null;
          is_public: boolean | null;
          created_at: string | null;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          name: string;
          item_type?: string | null;
          rarity?: string | null;
          requires_attunement?: boolean | null;
          description?: string | null;
          weight?: number | null;
          is_public?: boolean | null;
          created_at?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          name?: string;
          item_type?: string | null;
          rarity?: string | null;
          requires_attunement?: boolean | null;
          description?: string | null;
          weight?: number | null;
          is_public?: boolean | null;
          created_at?: string | null;
        };
        Relationships: [];
      };
      homebrew_monsters: {
        Row: {
          id: string;
          user_id: string | null;
          name: string;
          type: string | null;
          cr: string | null;
          size: string | null;
          hp: number | null;
          ac: number | null;
          speed: number | null;
          str: number | null;
          dex: number | null;
          con: number | null;
          int: number | null;
          wis: number | null;
          cha: number | null;
          attack_name: string | null;
          attack_bonus: number | null;
          attack_damage: string | null;
          xp: number | null;
          traits: string | null;
          is_public: boolean | null;
          created_at: string | null;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          name: string;
          type?: string | null;
          cr?: string | null;
          size?: string | null;
          hp?: number | null;
          ac?: number | null;
          speed?: number | null;
          str?: number | null;
          dex?: number | null;
          con?: number | null;
          int?: number | null;
          wis?: number | null;
          cha?: number | null;
          attack_name?: string | null;
          attack_bonus?: number | null;
          attack_damage?: string | null;
          xp?: number | null;
          traits?: string | null;
          is_public?: boolean | null;
          created_at?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          name?: string;
          type?: string | null;
          cr?: string | null;
          size?: string | null;
          hp?: number | null;
          ac?: number | null;
          speed?: number | null;
          str?: number | null;
          dex?: number | null;
          con?: number | null;
          int?: number | null;
          wis?: number | null;
          cha?: number | null;
          attack_name?: string | null;
          attack_bonus?: number | null;
          attack_damage?: string | null;
          xp?: number | null;
          traits?: string | null;
          is_public?: boolean | null;
          created_at?: string | null;
        };
        Relationships: [];
      };
      magic_items: {
        Row: {
          id: string;
          name: string;
          item_type: string;
          rarity: string;
          requires_attunement: boolean;
          description: string;
          weight: number | null;
          ac_bonus: number | null;
          save_bonus: number | null;
          attack_bonus: number | null;
          damage_bonus: number | null;
          max_charges: number | null;
          recharge: string | null;
          owner_id: string | null;
          source: string;
          is_public: boolean;
          ruleset_version: string | null;
          created_at: string;
          updated_at: string;
          recharge_dice: string | null;
          base_damage_dice: string | null;
        };
        Insert: {
          id: string;
          name: string;
          item_type: string;
          rarity: string;
          requires_attunement?: boolean;
          description: string;
          weight?: number | null;
          ac_bonus?: number | null;
          save_bonus?: number | null;
          attack_bonus?: number | null;
          damage_bonus?: number | null;
          max_charges?: number | null;
          recharge?: string | null;
          owner_id?: string | null;
          source?: string;
          is_public?: boolean;
          ruleset_version?: string | null;
          created_at?: string;
          updated_at?: string;
          recharge_dice?: string | null;
          base_damage_dice?: string | null;
        };
        Update: {
          id?: string;
          name?: string;
          item_type?: string;
          rarity?: string;
          requires_attunement?: boolean;
          description?: string;
          weight?: number | null;
          ac_bonus?: number | null;
          save_bonus?: number | null;
          attack_bonus?: number | null;
          damage_bonus?: number | null;
          max_charges?: number | null;
          recharge?: string | null;
          owner_id?: string | null;
          source?: string;
          is_public?: boolean;
          ruleset_version?: string | null;
          created_at?: string;
          updated_at?: string;
          recharge_dice?: string | null;
          base_damage_dice?: string | null;
        };
        Relationships: [];
      };
      monsters: {
        Row: {
          id: string;
          name: string;
          owner_id: string | null;
          source: string;
          visibility: string;
          type: string;
          subtype: string | null;
          alignment: string | null;
          cr: string;
          xp: number;
          size: string;
          hp: number;
          hp_formula: string;
          ac: number;
          ac_note: string | null;
          speed: number;
          fly_speed: number | null;
          swim_speed: number | null;
          climb_speed: number | null;
          burrow_speed: number | null;
          str: number;
          dex: number;
          con: number;
          int: number;
          wis: number;
          cha: number;
          saving_throws: Json | null;
          skills: Json | null;
          damage_immunities: string[] | null;
          damage_resistances: string[] | null;
          damage_vulnerabilities: string[] | null;
          condition_immunities: string[] | null;
          senses: Json | null;
          languages: string | null;
          proficiency_bonus: number | null;
          traits: Json | null;
          actions: Json | null;
          reactions: Json | null;
          legendary_actions: Json | null;
          legendary_resistance_count: number | null;
          attack_name: string | null;
          attack_bonus: number | null;
          attack_damage: string | null;
          created_at: string;
          updated_at: string;
          license_key: string | null;
          attribution_text: string | null;
          ruleset_version: string | null;
          is_editable: boolean | null;
        };
        Insert: {
          id: string;
          name: string;
          owner_id?: string | null;
          source?: string;
          visibility?: string;
          type: string;
          subtype?: string | null;
          alignment?: string | null;
          cr: string;
          xp: number;
          size: string;
          hp: number;
          hp_formula: string;
          ac: number;
          ac_note?: string | null;
          speed: number;
          fly_speed?: number | null;
          swim_speed?: number | null;
          climb_speed?: number | null;
          burrow_speed?: number | null;
          str: number;
          dex: number;
          con: number;
          int: number;
          wis: number;
          cha: number;
          saving_throws?: Json | null;
          skills?: Json | null;
          damage_immunities?: string[] | null;
          damage_resistances?: string[] | null;
          damage_vulnerabilities?: string[] | null;
          condition_immunities?: string[] | null;
          senses?: Json | null;
          languages?: string | null;
          proficiency_bonus?: number | null;
          traits?: Json | null;
          actions?: Json | null;
          reactions?: Json | null;
          legendary_actions?: Json | null;
          legendary_resistance_count?: number | null;
          attack_name?: string | null;
          attack_bonus?: number | null;
          attack_damage?: string | null;
          created_at?: string;
          updated_at?: string;
          license_key?: string | null;
          attribution_text?: string | null;
          ruleset_version?: string | null;
          is_editable?: boolean | null;
        };
        Update: {
          id?: string;
          name?: string;
          owner_id?: string | null;
          source?: string;
          visibility?: string;
          type?: string;
          subtype?: string | null;
          alignment?: string | null;
          cr?: string;
          xp?: number;
          size?: string;
          hp?: number;
          hp_formula?: string;
          ac?: number;
          ac_note?: string | null;
          speed?: number;
          fly_speed?: number | null;
          swim_speed?: number | null;
          climb_speed?: number | null;
          burrow_speed?: number | null;
          str?: number;
          dex?: number;
          con?: number;
          int?: number;
          wis?: number;
          cha?: number;
          saving_throws?: Json | null;
          skills?: Json | null;
          damage_immunities?: string[] | null;
          damage_resistances?: string[] | null;
          damage_vulnerabilities?: string[] | null;
          condition_immunities?: string[] | null;
          senses?: Json | null;
          languages?: string | null;
          proficiency_bonus?: number | null;
          traits?: Json | null;
          actions?: Json | null;
          reactions?: Json | null;
          legendary_actions?: Json | null;
          legendary_resistance_count?: number | null;
          attack_name?: string | null;
          attack_bonus?: number | null;
          attack_damage?: string | null;
          created_at?: string;
          updated_at?: string;
          license_key?: string | null;
          attribution_text?: string | null;
          ruleset_version?: string | null;
          is_editable?: boolean | null;
        };
        Relationships: [];
      };
      npcs: {
        Row: {
          id: string;
          campaign_id: string | null;
          name: string;
          role: string | null;
          race: string | null;
          location: string | null;
          faction: string | null;
          relationship: string | null;
          status: string | null;
          description: string | null;
          notes: string | null;
          last_seen: string | null;
          avatar_url: string | null;
          is_alive: boolean | null;
          created_at: string | null;
          updated_at: string | null;
          visible_to_players: boolean;
          in_combat: boolean;
          hp: number | null;
          max_hp: number | null;
          ac: number | null;
          initiative: number | null;
          conditions: string[] | null;
        };
        Insert: {
          id?: string;
          campaign_id?: string | null;
          name: string;
          role?: string | null;
          race?: string | null;
          location?: string | null;
          faction?: string | null;
          relationship?: string | null;
          status?: string | null;
          description?: string | null;
          notes?: string | null;
          last_seen?: string | null;
          avatar_url?: string | null;
          is_alive?: boolean | null;
          created_at?: string | null;
          updated_at?: string | null;
          visible_to_players?: boolean;
          in_combat?: boolean;
          hp?: number | null;
          max_hp?: number | null;
          ac?: number | null;
          initiative?: number | null;
          conditions?: string[] | null;
        };
        Update: {
          id?: string;
          campaign_id?: string | null;
          name?: string;
          role?: string | null;
          race?: string | null;
          location?: string | null;
          faction?: string | null;
          relationship?: string | null;
          status?: string | null;
          description?: string | null;
          notes?: string | null;
          last_seen?: string | null;
          avatar_url?: string | null;
          is_alive?: boolean | null;
          created_at?: string | null;
          updated_at?: string | null;
          visible_to_players?: boolean;
          in_combat?: boolean;
          hp?: number | null;
          max_hp?: number | null;
          ac?: number | null;
          initiative?: number | null;
          conditions?: string[] | null;
        };
        Relationships: [];
      };
      pending_attacks: {
        Row: {
          id: string;
          campaign_id: string;
          encounter_id: string | null;
          attacker_participant_id: string | null;
          attacker_name: string;
          attacker_type: string;
          target_participant_id: string | null;
          target_name: string;
          target_type: string | null;
          attack_source: string | null;
          attack_name: string;
          attack_kind: string;
          attack_bonus: number | null;
          target_ac: number | null;
          attack_d20: number | null;
          attack_total: number | null;
          hit_result: string | null;
          save_dc: number | null;
          save_ability: string | null;
          save_success_effect: string | null;
          save_d20: number | null;
          save_total: number | null;
          save_result: string | null;
          damage_dice: string | null;
          damage_type: string | null;
          damage_rolls: number[] | null;
          damage_raw: number | null;
          damage_final: number | null;
          damage_was_fudged: boolean;
          damage_fudge_reason: string | null;
          state: string;
          chain_id: string;
          declared_at: string;
          applied_at: string | null;
          created_at: string;
          updated_at: string;
          cover_level: string | null;
          damage_group_id: string | null;
          pending_lr_decision: boolean;
        };
        Insert: {
          id?: string;
          campaign_id: string;
          encounter_id?: string | null;
          attacker_participant_id?: string | null;
          attacker_name: string;
          attacker_type: string;
          target_participant_id?: string | null;
          target_name: string;
          target_type?: string | null;
          attack_source?: string | null;
          attack_name: string;
          attack_kind: string;
          attack_bonus?: number | null;
          target_ac?: number | null;
          attack_d20?: number | null;
          attack_total?: number | null;
          hit_result?: string | null;
          save_dc?: number | null;
          save_ability?: string | null;
          save_success_effect?: string | null;
          save_d20?: number | null;
          save_total?: number | null;
          save_result?: string | null;
          damage_dice?: string | null;
          damage_type?: string | null;
          damage_rolls?: number[] | null;
          damage_raw?: number | null;
          damage_final?: number | null;
          damage_was_fudged?: boolean;
          damage_fudge_reason?: string | null;
          state?: string;
          chain_id: string;
          declared_at?: string;
          applied_at?: string | null;
          created_at?: string;
          updated_at?: string;
          cover_level?: string | null;
          damage_group_id?: string | null;
          pending_lr_decision?: boolean;
        };
        Update: {
          id?: string;
          campaign_id?: string;
          encounter_id?: string | null;
          attacker_participant_id?: string | null;
          attacker_name?: string;
          attacker_type?: string;
          target_participant_id?: string | null;
          target_name?: string;
          target_type?: string | null;
          attack_source?: string | null;
          attack_name?: string;
          attack_kind?: string;
          attack_bonus?: number | null;
          target_ac?: number | null;
          attack_d20?: number | null;
          attack_total?: number | null;
          hit_result?: string | null;
          save_dc?: number | null;
          save_ability?: string | null;
          save_success_effect?: string | null;
          save_d20?: number | null;
          save_total?: number | null;
          save_result?: string | null;
          damage_dice?: string | null;
          damage_type?: string | null;
          damage_rolls?: number[] | null;
          damage_raw?: number | null;
          damage_final?: number | null;
          damage_was_fudged?: boolean;
          damage_fudge_reason?: string | null;
          state?: string;
          chain_id?: string;
          declared_at?: string;
          applied_at?: string | null;
          created_at?: string;
          updated_at?: string;
          cover_level?: string | null;
          damage_group_id?: string | null;
          pending_lr_decision?: boolean;
        };
        Relationships: [];
      };
      pending_concentration_saves: {
        Row: {
          id: string;
          campaign_id: string;
          encounter_id: string | null;
          chain_id: string;
          participant_id: string;
          character_id: string;
          spell_name: string;
          damage: number;
          dc: number;
          con_bonus: number;
          has_con_prof: boolean;
          state: string;
          offered_at: string;
          expires_at: string;
          decided_at: string | null;
          d20: number | null;
          total: number | null;
          result: string | null;
          resolution_source: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          campaign_id: string;
          encounter_id?: string | null;
          chain_id: string;
          participant_id: string;
          character_id: string;
          spell_name: string;
          damage: number;
          dc: number;
          con_bonus: number;
          has_con_prof: boolean;
          state?: string;
          offered_at?: string;
          expires_at: string;
          decided_at?: string | null;
          d20?: number | null;
          total?: number | null;
          result?: string | null;
          resolution_source?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          campaign_id?: string;
          encounter_id?: string | null;
          chain_id?: string;
          participant_id?: string;
          character_id?: string;
          spell_name?: string;
          damage?: number;
          dc?: number;
          con_bonus?: number;
          has_con_prof?: boolean;
          state?: string;
          offered_at?: string;
          expires_at?: string;
          decided_at?: string | null;
          d20?: number | null;
          total?: number | null;
          result?: string | null;
          resolution_source?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      pending_death_saves: {
        Row: {
          id: string;
          campaign_id: string;
          encounter_id: string | null;
          participant_id: string;
          character_id: string;
          state: string;
          d20: number | null;
          result: string | null;
          successes_after: number | null;
          failures_after: number | null;
          created_at: string;
          resolved_at: string | null;
        };
        Insert: {
          id?: string;
          campaign_id: string;
          encounter_id?: string | null;
          participant_id: string;
          character_id: string;
          state?: string;
          d20?: number | null;
          result?: string | null;
          successes_after?: number | null;
          failures_after?: number | null;
          created_at?: string;
          resolved_at?: string | null;
        };
        Update: {
          id?: string;
          campaign_id?: string;
          encounter_id?: string | null;
          participant_id?: string;
          character_id?: string;
          state?: string;
          d20?: number | null;
          result?: string | null;
          successes_after?: number | null;
          failures_after?: number | null;
          created_at?: string;
          resolved_at?: string | null;
        };
        Relationships: [];
      };
      pending_reactions: {
        Row: {
          id: string;
          campaign_id: string;
          pending_attack_id: string | null;
          reactor_participant_id: string;
          reactor_name: string;
          reactor_type: string;
          reaction_key: string;
          reaction_name: string;
          trigger_point: string;
          offered_at: string;
          expires_at: string;
          decided_at: string | null;
          state: string;
          decision_payload: Json | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          campaign_id: string;
          pending_attack_id?: string | null;
          reactor_participant_id: string;
          reactor_name: string;
          reactor_type: string;
          reaction_key: string;
          reaction_name: string;
          trigger_point: string;
          offered_at?: string;
          expires_at: string;
          decided_at?: string | null;
          state?: string;
          decision_payload?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          campaign_id?: string;
          pending_attack_id?: string | null;
          reactor_participant_id?: string;
          reactor_name?: string;
          reactor_type?: string;
          reaction_key?: string;
          reaction_name?: string;
          trigger_point?: string;
          offered_at?: string;
          expires_at?: string;
          decided_at?: string | null;
          state?: string;
          decision_payload?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      pending_spell_casts: {
        Row: {
          id: string;
          campaign_id: string;
          encounter_id: string | null;
          chain_id: string;
          caster_participant_id: string | null;
          caster_character_id: string | null;
          caster_name: string;
          spell_name: string;
          spell_level: number;
          is_cantrip: boolean;
          state: string;
          declared_at: string;
          expires_at: string;
          resolved_at: string | null;
          counterspell_attack_id: string | null;
          outcome: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          campaign_id: string;
          encounter_id?: string | null;
          chain_id: string;
          caster_participant_id?: string | null;
          caster_character_id?: string | null;
          caster_name: string;
          spell_name: string;
          spell_level: number;
          is_cantrip?: boolean;
          state?: string;
          declared_at?: string;
          expires_at: string;
          resolved_at?: string | null;
          counterspell_attack_id?: string | null;
          outcome?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          campaign_id?: string;
          encounter_id?: string | null;
          chain_id?: string;
          caster_participant_id?: string | null;
          caster_character_id?: string | null;
          caster_name?: string;
          spell_name?: string;
          spell_level?: number;
          is_cantrip?: boolean;
          state?: string;
          declared_at?: string;
          expires_at?: string;
          resolved_at?: string | null;
          counterspell_attack_id?: string | null;
          outcome?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      profiles: {
        Row: {
          id: string;
          email: string;
          display_name: string | null;
          subscription_tier: string;
          stripe_customer_id: string | null;
          stripe_subscription_id: string | null;
          subscription_status: string;
          created_at: string;
          updated_at: string;
          active_dice_skin: string | null;
          extra_character_slots: number;
        };
        Insert: {
          id: string;
          email: string;
          display_name?: string | null;
          subscription_tier?: string;
          stripe_customer_id?: string | null;
          stripe_subscription_id?: string | null;
          subscription_status?: string;
          created_at?: string;
          updated_at?: string;
          active_dice_skin?: string | null;
          extra_character_slots?: number;
        };
        Update: {
          id?: string;
          email?: string;
          display_name?: string | null;
          subscription_tier?: string;
          stripe_customer_id?: string | null;
          stripe_subscription_id?: string | null;
          subscription_status?: string;
          created_at?: string;
          updated_at?: string;
          active_dice_skin?: string | null;
          extra_character_slots?: number;
        };
        Relationships: [];
      };
      roll_log_reactions: {
        Row: {
          id: string;
          roll_id: string;
          user_id: string;
          character_name: string;
          emoji: string;
          created_at: string | null;
        };
        Insert: {
          id?: string;
          roll_id: string;
          user_id: string;
          character_name?: string;
          emoji: string;
          created_at?: string | null;
        };
        Update: {
          id?: string;
          roll_id?: string;
          user_id?: string;
          character_name?: string;
          emoji?: string;
          created_at?: string | null;
        };
        Relationships: [];
      };
      roll_logs: {
        Row: {
          id: string;
          user_id: string;
          character_id: string | null;
          campaign_id: string | null;
          label: string;
          dice_expression: string;
          individual_results: number[];
          total: number;
          rolled_at: string;
          modifier: number | null;
          character_name: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          character_id?: string | null;
          campaign_id?: string | null;
          label: string;
          dice_expression: string;
          individual_results: number[];
          total: number;
          rolled_at?: string;
          modifier?: number | null;
          character_name?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          character_id?: string | null;
          campaign_id?: string | null;
          label?: string;
          dice_expression?: string;
          individual_results?: number[];
          total?: number;
          rolled_at?: string;
          modifier?: number | null;
          character_name?: string;
        };
        Relationships: [];
      };
      roll_requests: {
        Row: {
          id: string;
          campaign_id: string;
          requested_by: string;
          target_character_id: string | null;
          target_name: string;
          roll_type: string;
          roll_name: string;
          dc: number | null;
          status: string;
          result: number | null;
          success: boolean | null;
          rolled_by_name: string | null;
          created_at: string;
          completed_at: string | null;
        };
        Insert: {
          id?: string;
          campaign_id: string;
          requested_by: string;
          target_character_id?: string | null;
          target_name?: string;
          roll_type?: string;
          roll_name?: string;
          dc?: number | null;
          status?: string;
          result?: number | null;
          success?: boolean | null;
          rolled_by_name?: string | null;
          created_at?: string;
          completed_at?: string | null;
        };
        Update: {
          id?: string;
          campaign_id?: string;
          requested_by?: string;
          target_character_id?: string | null;
          target_name?: string;
          roll_type?: string;
          roll_name?: string;
          dc?: number | null;
          status?: string;
          result?: number | null;
          success?: boolean | null;
          rolled_by_name?: string | null;
          created_at?: string;
          completed_at?: string | null;
        };
        Relationships: [];
      };
      scene_drawings: {
        Row: {
          id: string;
          scene_id: string;
          kind: string;
          points: Json;
          color: string;
          line_width: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          scene_id: string;
          kind: string;
          points?: Json;
          color?: string;
          line_width?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          scene_id?: string;
          kind?: string;
          points?: Json;
          color?: string;
          line_width?: number;
          created_at?: string;
        };
        Relationships: [];
      };
      scene_texts: {
        Row: {
          id: string;
          scene_id: string;
          x: number;
          y: number;
          text: string;
          color: string;
          font_size: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          scene_id: string;
          x: number;
          y: number;
          text?: string;
          color?: string;
          font_size?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          scene_id?: string;
          x?: number;
          y?: number;
          text?: string;
          color?: string;
          font_size?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      scene_tokens: {
        Row: {
          id: string;
          scene_id: string;
          x: number;
          y: number;
          size: string;
          rotation: number;
          image_storage_path: string | null;
          name: string;
          character_id: string | null;
          npc_id: string | null;
          player_id: string | null;
          visible_to_all: boolean;
          z_index: number;
          created_at: string;
          updated_at: string;
          color: number;
        };
        Insert: {
          id?: string;
          scene_id: string;
          x?: number;
          y?: number;
          size?: string;
          rotation?: number;
          image_storage_path?: string | null;
          name?: string;
          character_id?: string | null;
          npc_id?: string | null;
          player_id?: string | null;
          visible_to_all?: boolean;
          z_index?: number;
          created_at?: string;
          updated_at?: string;
          color?: number;
        };
        Update: {
          id?: string;
          scene_id?: string;
          x?: number;
          y?: number;
          size?: string;
          rotation?: number;
          image_storage_path?: string | null;
          name?: string;
          character_id?: string | null;
          npc_id?: string | null;
          player_id?: string | null;
          visible_to_all?: boolean;
          z_index?: number;
          created_at?: string;
          updated_at?: string;
          color?: number;
        };
        Relationships: [];
      };
      scene_walls: {
        Row: {
          id: string;
          scene_id: string;
          x1: number;
          y1: number;
          x2: number;
          y2: number;
          blocks_sight: boolean;
          blocks_movement: boolean;
          door_state: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          scene_id: string;
          x1: number;
          y1: number;
          x2: number;
          y2: number;
          blocks_sight?: boolean;
          blocks_movement?: boolean;
          door_state?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          scene_id?: string;
          x1?: number;
          y1?: number;
          x2?: number;
          y2?: number;
          blocks_sight?: boolean;
          blocks_movement?: boolean;
          door_state?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      scenes: {
        Row: {
          id: string;
          campaign_id: string;
          owner_id: string;
          name: string;
          grid_type: string;
          grid_size_px: number;
          width_cells: number;
          height_cells: number;
          background_storage_path: string | null;
          dm_notes: string | null;
          is_published: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          campaign_id: string;
          owner_id: string;
          name?: string;
          grid_type?: string;
          grid_size_px?: number;
          width_cells?: number;
          height_cells?: number;
          background_storage_path?: string | null;
          dm_notes?: string | null;
          is_published?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          campaign_id?: string;
          owner_id?: string;
          name?: string;
          grid_type?: string;
          grid_size_px?: number;
          width_cells?: number;
          height_cells?: number;
          background_storage_path?: string | null;
          dm_notes?: string | null;
          is_published?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      schedule_availability: {
        Row: {
          id: string;
          schedule_id: string | null;
          user_id: string | null;
          discord_user_id: string | null;
          player_name: string;
          available_dates: Json | null;
          notes: string | null;
          responded_at: string | null;
        };
        Insert: {
          id?: string;
          schedule_id?: string | null;
          user_id?: string | null;
          discord_user_id?: string | null;
          player_name?: string;
          available_dates?: Json | null;
          notes?: string | null;
          responded_at?: string | null;
        };
        Update: {
          id?: string;
          schedule_id?: string | null;
          user_id?: string | null;
          discord_user_id?: string | null;
          player_name?: string;
          available_dates?: Json | null;
          notes?: string | null;
          responded_at?: string | null;
        };
        Relationships: [];
      };
      session_schedules: {
        Row: {
          id: string;
          campaign_id: string | null;
          created_by: string | null;
          title: string | null;
          description: string | null;
          proposed_dates: Json | null;
          confirmed_date: string | null;
          location: string | null;
          deadline: string | null;
          discord_message_id: string | null;
          discord_channel_id: string | null;
          status: string | null;
          created_at: string | null;
        };
        Insert: {
          id?: string;
          campaign_id?: string | null;
          created_by?: string | null;
          title?: string | null;
          description?: string | null;
          proposed_dates?: Json | null;
          confirmed_date?: string | null;
          location?: string | null;
          deadline?: string | null;
          discord_message_id?: string | null;
          discord_channel_id?: string | null;
          status?: string | null;
          created_at?: string | null;
        };
        Update: {
          id?: string;
          campaign_id?: string | null;
          created_by?: string | null;
          title?: string | null;
          description?: string | null;
          proposed_dates?: Json | null;
          confirmed_date?: string | null;
          location?: string | null;
          deadline?: string | null;
          discord_message_id?: string | null;
          discord_channel_id?: string | null;
          status?: string | null;
          created_at?: string | null;
        };
        Relationships: [];
      };
      session_states: {
        Row: {
          id: string;
          campaign_id: string;
          initiative_order: Json;
          current_turn: number;
          round: number;
          combat_active: boolean;
          updated_at: string;
        };
        Insert: {
          id?: string;
          campaign_id: string;
          initiative_order?: Json;
          current_turn?: number;
          round?: number;
          combat_active?: boolean;
          updated_at?: string;
        };
        Update: {
          id?: string;
          campaign_id?: string;
          initiative_order?: Json;
          current_turn?: number;
          round?: number;
          combat_active?: boolean;
          updated_at?: string;
        };
        Relationships: [];
      };
      session_summaries: {
        Row: {
          id: string;
          campaign_id: string | null;
          title: string | null;
          summary: string;
          highlights: Json | null;
          session_date: string | null;
          generated_at: string | null;
        };
        Insert: {
          id?: string;
          campaign_id?: string | null;
          title?: string | null;
          summary: string;
          highlights?: Json | null;
          session_date?: string | null;
          generated_at?: string | null;
        };
        Update: {
          id?: string;
          campaign_id?: string | null;
          title?: string | null;
          summary?: string;
          highlights?: Json | null;
          session_date?: string | null;
          generated_at?: string | null;
        };
        Relationships: [];
      };
      spells: {
        Row: {
          id: string;
          name: string;
          owner_id: string | null;
          source: string;
          visibility: string;
          level: number;
          school: string;
          casting_time: string;
          range: string;
          components: string;
          duration: string;
          concentration: boolean;
          ritual: boolean;
          classes: string[];
          description: string;
          higher_levels: string | null;
          save_type: string | null;
          attack_type: string | null;
          damage_dice: string | null;
          damage_type: string | null;
          damage_at_slot_level: Json | null;
          damage_at_char_level: Json | null;
          heal_dice: string | null;
          heal_at_slot_level: Json | null;
          area_of_effect: Json | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          name: string;
          owner_id?: string | null;
          source?: string;
          visibility?: string;
          level: number;
          school: string;
          casting_time?: string;
          range?: string;
          components?: string;
          duration?: string;
          concentration?: boolean;
          ritual?: boolean;
          classes?: string[];
          description?: string;
          higher_levels?: string | null;
          save_type?: string | null;
          attack_type?: string | null;
          damage_dice?: string | null;
          damage_type?: string | null;
          damage_at_slot_level?: Json | null;
          damage_at_char_level?: Json | null;
          heal_dice?: string | null;
          heal_at_slot_level?: Json | null;
          area_of_effect?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          owner_id?: string | null;
          source?: string;
          visibility?: string;
          level?: number;
          school?: string;
          casting_time?: string;
          range?: string;
          components?: string;
          duration?: string;
          concentration?: boolean;
          ritual?: boolean;
          classes?: string[];
          description?: string;
          higher_levels?: string | null;
          save_type?: string | null;
          attack_type?: string | null;
          damage_dice?: string | null;
          damage_type?: string | null;
          damage_at_slot_level?: Json | null;
          damage_at_char_level?: Json | null;
          heal_dice?: string | null;
          heal_at_slot_level?: Json | null;
          area_of_effect?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      token_notes: {
        Row: {
          id: string;
          campaign_id: string;
          token_key: string;
          author_id: string | null;
          author_name: string;
          note: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          campaign_id: string;
          token_key: string;
          author_id?: string | null;
          author_name?: string;
          note?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          campaign_id?: string;
          token_key?: string;
          author_id?: string | null;
          author_name?: string;
          note?: string;
          created_at?: string;
        };
        Relationships: [];
      };
    };
    Views: { [_ in never]: never };
    Functions: { [_ in never]: never };
    Enums: { [_ in never]: never };
    CompositeTypes: { [_ in never]: never };
  };
};

// Convenience aliases — saves typing `Database['public']['Tables']['x']['Row']`
// in every consumer file. Use these for new code; keep the deep-key
// form when echoing supabase-js's own type signatures (RPC return shapes etc.).
type Tables = Database['public']['Tables'];
export type TableRow<T extends keyof Tables> = Tables[T]['Row'];
export type TableInsert<T extends keyof Tables> = Tables[T]['Insert'];
export type TableUpdate<T extends keyof Tables> = Tables[T]['Update'];
