// @vitest-environment happy-dom
import {afterEach,beforeEach,expect,it,vi} from 'vitest';
import {cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import type {Character} from '../../../types';
const m=vi.hoisted(()=>({begin:vi.fn(),finish:vi.fn(),context:vi.fn(),list:vi.fn(),resume:vi.fn(),roll:vi.fn(),combat:vi.fn()}));
vi.mock('../../../lib/supabase',()=>({supabase:{}}));
vi.mock('../../../lib/api/psionicPropel',async()=>({...await vi.importActual('../../../lib/api/psionicPropel'),beginPropel:m.begin,finishPropel:m.finish,getPropelContext:m.context,listPropel:m.list}));
vi.mock('../../../lib/api/psionicDamage',()=>({loadPsionicDamageContext:m.combat}));
vi.mock('../../../lib/gameUtils',()=>({classSaveDC:(c:Character)=>c.intelligence}));
vi.mock('../../../rules/dice',()=>({rollDie:m.roll}));
vi.mock('./continuePropel',()=>({continuePropel:m.resume}));
import PropelControls from './PropelControls';
import {pendingPropel} from '../../../lib/propelRecovery';
const character={id:'00000000-0000-4000-8000-000000000001',name:'Hero',class_name:'Psion',level:5,intelligence:16,class_resources:{'psionic-energy-dice':2}} as unknown as Character;
const row={request_id:'00000000-0000-4000-8000-000000000002',target:{name:'Goblin'},caster_snapshot:{...character,intelligence:15},mode:'powered',movement:'push',base_roll:3,roll_result:{total:3},outcome:null};
beforeEach(()=>{localStorage.clear();vi.resetAllMocks();m.context.mockResolvedValue({bonusAvailable:true,turnId:'turn',encounterId:null});m.list.mockResolvedValue({items:[],nextCursor:null});m.roll.mockReturnValue(3);m.begin.mockResolvedValue(row);m.resume.mockResolvedValue(row);m.finish.mockResolvedValue({...row,outcome:'passed',result:{energyCost:0}});});
afterEach(cleanup);
async function open(){fireEvent.click(screen.getByRole('button',{name:'Use / resume'}));await waitFor(()=>expect((screen.getByLabelText('Target') as HTMLInputElement).disabled).toBe(false));}
async function choose(){await open();fireEvent.change(screen.getByLabelText('Target'),{target:{value:'Goblin'}});fireEvent.click(screen.getByRole('checkbox'));fireEvent.change(screen.getByLabelText('Movement'),{target:{value:'powered'}});}
it('does not roll or declare before a legal target is confirmed',async()=>{render(<PropelControls character={character}/>);await open();expect((screen.getByRole('button',{name:'Declare Bonus Action'}) as HTMLButtonElement).disabled).toBe(true);fireEvent.click(screen.getByRole('button',{name:'Close for later'}));expect(m.roll).not.toHaveBeenCalled();expect(m.begin).not.toHaveBeenCalled();});
it('declares once, freezes target and uses the saved caster DC',async()=>{render(<PropelControls character={character}/>);await choose();const button=screen.getByRole('button',{name:'Declare Bonus Action'});fireEvent.click(button);fireEvent.click(button);await screen.findByText(/Strength save DC 15/);expect(m.begin).toHaveBeenCalledTimes(1);expect(m.begin.mock.calls[0][1]).toMatchObject({mode:'powered',roll:3,target:{name:'Goblin',legalTargetConfirmed:true}});expect(m.roll).toHaveBeenCalledTimes(1);expect(pendingPropel(character.id)).toEqual([]);fireEvent.click(screen.getByRole('button',{name:'Save passed'}));await screen.findByRole('status');expect(m.finish).toHaveBeenCalledWith(character.id,row.request_id,'passed');});
it('keeps an uncertain declaration and retries the exact saved roll',async()=>{m.begin.mockRejectedValueOnce(new Error('Lost reply'));render(<PropelControls character={character}/>);await choose();fireEvent.click(screen.getByRole('button',{name:'Declare Bonus Action'}));await screen.findByRole('button',{name:'Confirm saved use'});expect(pendingPropel(character.id)).toHaveLength(1);fireEvent.click(screen.getByRole('button',{name:'Confirm saved use'}));await screen.findByText(/Strength save DC 15/);expect(m.begin.mock.calls[0]).toEqual(m.begin.mock.calls[1]);expect(m.roll).toHaveBeenCalledTimes(1);});
it('keeps an uncertain save outcome instead of permitting a different outcome',async()=>{m.finish.mockRejectedValueOnce(new Error('Lost reply'));render(<PropelControls character={character}/>);await choose();fireEvent.click(screen.getByRole('button',{name:'Declare Bonus Action'}));await screen.findByRole('button',{name:'Save failed'});fireEvent.click(screen.getByRole('button',{name:'Save failed'}));await screen.findByRole('button',{name:'Confirm saved failed result'});expect((screen.getByRole('button',{name:'Save passed'}) as HTMLButtonElement).disabled).toBe(true);expect(pendingPropel(character.id)).toMatchObject([{kind:'finish',request:{outcome:'failed'}}]);});
it('rejects a turn change before any roll or declaration',async()=>{render(<PropelControls character={character}/>);await choose();m.context.mockResolvedValue({bonusAvailable:true,turnId:'later',encounterId:null});fireEvent.click(screen.getByRole('button',{name:'Declare Bonus Action'}));await screen.findByRole('alert');expect(m.begin).not.toHaveBeenCalled();expect(m.roll).not.toHaveBeenCalled();});
