// @vitest-environment happy-dom
import {cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {afterEach,expect,it,vi} from 'vitest';
import type {PsionicEnhancementPersistence} from '../../../lib/api/psionicTurns';
import Panel from './PsionicEffectRecoveryPanel';
afterEach(cleanup);
const row={requestId:'saved',characterId:'hero',discipline:'destructive-thoughts',context:{targetName:'Goblin'},total:9,finalized:false,applied:false,expiredByLongRest:false};
const service=(read:ReturnType<typeof vi.fn>)=>({getEffectRolls:read} as unknown as PsionicEnhancementPersistence);
it('resumes the exact matching character and discipline record',async()=>{const resume=vi.fn();render(<Panel characterId="hero" persistence={service(vi.fn(async()=>[row,{...row,requestId:'other',characterId:'other'},{...row,requestId:'bio',discipline:'biofeedback'}]))} discipline="destructive-thoughts" disabled={false} onResume={resume}/>);fireEvent.click(await screen.findByRole('button',{name:/Resume paid roll/}));expect(resume).toHaveBeenCalledWith('saved');expect(screen.getAllByRole('button')).toHaveLength(1);});
it('offers a refresh after a read failure',async()=>{const read=vi.fn().mockRejectedValueOnce(new Error('Offline')).mockResolvedValue([row]);render(<Panel characterId="hero" persistence={service(read)} discipline="destructive-thoughts" disabled={false} onResume={vi.fn()}/>);expect(await screen.findByRole('alert')).toHaveProperty('textContent','Offline');fireEvent.click(screen.getByRole('button',{name:'Refresh saved rolls'}));await screen.findByRole('button',{name:/Resume paid roll/});expect(screen.queryByRole('alert')).toBeNull();});
it('ignores a late response from the previous character',async()=>{let resolve!:(v:unknown)=>void;const read=vi.fn().mockImplementationOnce(()=>new Promise(r=>resolve=r)).mockResolvedValue([]),p=service(read);const view=render(<Panel characterId="hero" persistence={p} discipline="destructive-thoughts" disabled={false} onResume={vi.fn()}/>);view.rerender(<Panel characterId="other" persistence={p} discipline="destructive-thoughts" disabled={false} onResume={vi.fn()}/>);resolve([row]);await waitFor(()=>expect(read).toHaveBeenCalledTimes(2));expect(screen.queryByRole('button')).toBeNull();});

it('does not repeat the result already displayed by the sheet',async()=>{const read=vi.fn(async()=>[row]);const view=render(<Panel characterId="hero" persistence={service(read)} discipline="destructive-thoughts" currentResultId="saved" disabled={false} onResume={vi.fn()}/>);await waitFor(()=>expect(read).toHaveBeenCalled());expect(screen.queryByRole('button')).toBeNull();view.rerender(<Panel characterId="hero" persistence={service(read)} discipline="destructive-thoughts" disabled={false} onResume={vi.fn()}/>);await screen.findByRole('button',{name:/Resume paid roll/});});

it('explains an expired benefit without offering to grant it',async()=>{const resume=vi.fn();render(<Panel characterId="hero" persistence={service(vi.fn(async()=>[{...row,discipline:'biofeedback',expiredByLongRest:true}]))} discipline="biofeedback" disabled={false} onResume={resume}/>);const button=await screen.findByRole('button',{name:/Expired after Long Rest/});expect((button as HTMLButtonElement).disabled).toBe(true);fireEvent.click(button);expect(resume).not.toHaveBeenCalled();});
