-- v2.310.0 — Combat Phase 3 pt 2: backfill from characters/npcs/scene_tokens.
-- See docs/COMBAT_PHASE_3_TOKEN_LIBRARY.md.
-- Idempotent — uses NOT EXISTS guards so re-run is safe.
--
-- Plan:
--   Step 1: extend definition_type enum to add 'narrative_npc'
--           (existing npcs table is distinct from dm_npc_roster)
--   Step 2: combatants from characters (campaigned PCs only)
--   Step 3: combatants from npcs
--   Step 4: combatants from orphan scene_tokens
--           — name match against canonical monsters (case-insensitive)
--             yields 'srd_monster'; otherwise 'custom'
--           — REUSES scene_token.id as combatant.id for stable backref
--             in step 5
--   Step 5: placements from scene_tokens
--           — resolves combatant_id via 3-way COALESCE (char/npc/orphan)
--           — preserves visual fidelity (size, color, image_storage_path
--             stored as placement overrides)

-- ===================================================================
-- Step 1: extend the definition_type CHECK to include 'narrative_npc'
-- ===================================================================

ALTER TABLE public.combatants
  DROP CONSTRAINT IF EXISTS combatants_definition_type_check;

ALTER TABLE public.combatants
  ADD CONSTRAINT combatants_definition_type_check
  CHECK (definition_type IN (
    'character',
    'srd_monster',
    'homebrew_monster',
    'roster_npc',
    'narrative_npc',
    'custom'
  ));

-- ===================================================================
-- Step 2: combatants from characters (campaigned PCs only)
-- ===================================================================

INSERT INTO public.combatants (
  campaign_id, owner_id, name, portrait_storage_path,
  definition_type, definition_id, stat_block_snapshot,
  current_hp, max_hp, temp_hp,
  active_conditions, exhaustion_level,
  death_save_successes, death_save_failures,
  created_at, updated_at, last_used_at
)
SELECT
  ch.campaign_id,
  c.owner_id,                  -- DM owns the combatant; player accesses
                                -- their own PC combatant via RLS path
  ch.name,
  ch.avatar_url,
  'character',
  ch.id::text,
  to_jsonb(ch.*),
  ch.current_hp,
  ch.max_hp,
  ch.temp_hp,
  ch.active_conditions,
  ch.exhaustion_level,
  ch.death_saves_successes,
  ch.death_saves_failures,
  ch.created_at,
  now(),
  now()
FROM public.characters ch
JOIN public.campaigns c ON c.id = ch.campaign_id
WHERE ch.campaign_id IS NOT NULL
  AND NOT EXISTS (
    SELECT 1 FROM public.combatants cb
    WHERE cb.definition_type = 'character'
      AND cb.definition_id = ch.id::text
      AND cb.campaign_id = ch.campaign_id
  );

-- ===================================================================
-- Step 3: combatants from npcs
-- ===================================================================

INSERT INTO public.combatants (
  campaign_id, owner_id, name, portrait_storage_path,
  definition_type, definition_id, stat_block_snapshot,
  current_hp, max_hp,
  active_conditions,
  created_at, updated_at, last_used_at
)
SELECT
  n.campaign_id,
  c.owner_id,
  n.name,
  n.avatar_url,
  'narrative_npc',
  n.id::text,
  to_jsonb(n.*),
  COALESCE(n.hp, 0),
  COALESCE(n.max_hp, 0),
  COALESCE(n.conditions, ARRAY[]::text[]),
  COALESCE(n.created_at, now()),
  now(),
  now()
FROM public.npcs n
JOIN public.campaigns c ON c.id = n.campaign_id
WHERE n.campaign_id IS NOT NULL
  AND NOT EXISTS (
    SELECT 1 FROM public.combatants cb
    WHERE cb.definition_type = 'narrative_npc'
      AND cb.definition_id = n.id::text
      AND cb.campaign_id = n.campaign_id
  );

-- ===================================================================
-- Step 4: combatants from orphan scene_tokens
-- ===================================================================
-- Reuses scene_token.id as combatant.id so step 5 can resolve the
-- placement→combatant link without a CTE or extra column. This is
-- safe because a UUID generated by gen_random_uuid() in scene_tokens
-- is unique across the database and won't collide with combatants
-- generated for steps 2/3 (which use fresh gen_random_uuid()).

INSERT INTO public.combatants (
  id,
  campaign_id, owner_id, name, portrait_storage_path,
  definition_type, definition_id, stat_block_snapshot,
  current_hp, max_hp,
  created_at, updated_at, last_used_at
)
SELECT
  st.id,                        -- reuse scene_token id as combatant id
  s.campaign_id,
  c.owner_id,
  st.name,
  NULL,                         -- portrait stays on placement override
  CASE WHEN m.id IS NOT NULL THEN 'srd_monster' ELSE 'custom' END,
  m.id,                         -- NULL when no name match
  COALESCE(to_jsonb(m.*), '{}'::jsonb),
  COALESCE(m.hp, 0),
  COALESCE(m.hp, 0),
  st.created_at,
  now(),
  now()
FROM public.scene_tokens st
JOIN public.scenes s ON s.id = st.scene_id
JOIN public.campaigns c ON c.id = s.campaign_id
LEFT JOIN public.monsters m
  ON LOWER(m.name) = LOWER(st.name)
  AND m.owner_id IS NULL        -- canonical SRD only; homebrew matching
                                 -- could miss-classify so we skip it
WHERE st.character_id IS NULL
  AND st.npc_id IS NULL
  AND NOT EXISTS (
    SELECT 1 FROM public.combatants cb
    WHERE cb.id = st.id
  );

-- ===================================================================
-- Step 5: placements from scene_tokens
-- ===================================================================
-- One placement per scene_token. combatant_id resolved via 3-way
-- COALESCE based on the source FK (character_id / npc_id / orphan).

INSERT INTO public.scene_token_placements (
  scene_id, combatant_id,
  x, y, rotation, z_index,
  size_override, color_override, image_storage_path_override,
  visible_to_all,
  created_at, updated_at
)
SELECT
  st.scene_id,
  COALESCE(
    -- PC token → combatant where definition_type='character' AND
    -- definition_id matches character_id
    (SELECT cb.id FROM public.combatants cb
       WHERE cb.definition_type = 'character'
         AND cb.definition_id = st.character_id::text
         AND cb.campaign_id = s.campaign_id
       LIMIT 1),
    -- NPC token → combatant where definition_type='narrative_npc' AND
    -- definition_id matches npc_id
    (SELECT cb.id FROM public.combatants cb
       WHERE cb.definition_type = 'narrative_npc'
         AND cb.definition_id = st.npc_id::text
         AND cb.campaign_id = s.campaign_id
       LIMIT 1),
    -- Orphan token → combatant whose id matches the scene_token id
    -- (we set this in step 4)
    (SELECT cb.id FROM public.combatants cb WHERE cb.id = st.id LIMIT 1)
  ) AS combatant_id,
  st.x, st.y, st.rotation, st.z_index,
  -- Visual fidelity preserved as overrides. v2.315 cleanup can null
  -- these out where they match the combatant's inferred defaults.
  st.size,
  st.color,
  st.image_storage_path,
  st.visible_to_all,
  st.created_at,
  now()
FROM public.scene_tokens st
JOIN public.scenes s ON s.id = st.scene_id
WHERE NOT EXISTS (
  -- Dedupe on (scene_id, exact x/y) — sufficient because two tokens
  -- can't physically occupy the same position at backfill time
  SELECT 1 FROM public.scene_token_placements p
  WHERE p.scene_id = st.scene_id
    AND p.x = st.x
    AND p.y = st.y
);
