-- v2.394.0 — join_campaign_by_code RPC.
--
-- Background. The campaigns RLS policy requires SELECT-via-membership:
-- non-members can't see a row, so they can't look it up by join_code.
-- That blocks the obvious "type the code and join" flow that DMs
-- have been telling players to use (the join_code is shown in
-- CampaignSettings + SessionTab as if it were usable, but no UI ever
-- consumed it). This RPC closes the loop: a SECURITY DEFINER function
-- can look up the campaign on behalf of a non-member, validate the
-- code, and create the membership row.
--
-- Security model:
--   - Code lookup is exact match, case-insensitive trim. Codes are
--     opaque tokens generated by generate_join_code(); a 6-char base-32
--     space (~10^9) plus rate limiting on the auth layer is enough
--     friction for a casual sharing token. We do NOT support "list all
--     campaigns" or partial matching — that would turn this into an
--     enumeration oracle.
--   - The function only INSERTs into campaign_members; it never
--     mutates campaigns or any other table. If the caller is already
--     a member, returns the existing campaign row (idempotent).
--   - Role on insert: 'player'. DM membership is created at campaign
--     creation time elsewhere; this RPC won't accidentally promote.
--   - Returns the joined campaign's id + name so the client can
--     navigate to it without a separate fetch (which would fail RLS
--     on campaigns until the membership insert echoes through the
--     auth_user_campaign_ids() materialization, which can lag a tick).

CREATE OR REPLACE FUNCTION public.join_campaign_by_code(p_code text)
RETURNS TABLE(campaign_id uuid, campaign_name text, already_member boolean)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_uid       uuid := auth.uid();
  v_code      text := upper(btrim(coalesce(p_code, '')));
  v_camp_id   uuid;
  v_camp_name text;
  v_already   boolean;
BEGIN
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'Not authenticated' USING ERRCODE = '28000';
  END IF;

  IF length(v_code) = 0 THEN
    RAISE EXCEPTION 'Join code is required' USING ERRCODE = '22023';
  END IF;

  SELECT id, name INTO v_camp_id, v_camp_name
    FROM public.campaigns
   WHERE upper(btrim(join_code)) = v_code
   LIMIT 1;

  IF v_camp_id IS NULL THEN
    RAISE EXCEPTION 'No campaign matches that join code' USING ERRCODE = 'P0002';
  END IF;

  SELECT EXISTS (
    SELECT 1 FROM public.campaign_members
     WHERE campaign_id = v_camp_id AND user_id = v_uid
  ) INTO v_already;

  IF NOT v_already THEN
    INSERT INTO public.campaign_members (campaign_id, user_id, role)
    VALUES (v_camp_id, v_uid, 'player');
  END IF;

  RETURN QUERY SELECT v_camp_id, v_camp_name, v_already;
END;
$$;

REVOKE ALL ON FUNCTION public.join_campaign_by_code(text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.join_campaign_by_code(text) TO authenticated;
