-- v2.298.0 — Repo back-fill. This migration was originally
-- applied to live as version 20260418160145 (name 'seed_spells_chunk_08_final') but
-- never committed to the source tree. v2.298 reconciles the
-- ~112-migration gap between live's schema_migrations history
-- and the repo's supabase/migrations/ directory. Statements
-- below are verbatim from supabase_migrations.schema_migrations
-- on the live database.
--
-- This is a no-op on live (already applied at this version)
-- and a clean apply on a fresh DB provisioned from the repo.

INSERT INTO public.spells (id, name, owner_id, source, visibility, level, school, casting_time, "range", components, duration, concentration, ritual, classes, description, higher_levels, save_type, attack_type, damage_dice, damage_type, damage_at_slot_level, damage_at_char_level, heal_dice, heal_at_slot_level, area_of_effect) VALUES
('thought-form', 'Thought Form', NULL, 'ua', 'private', 6, 'Transmutation', '1 bonus action', 'Self', 'V, M (brain matter in a vessel worth 500+ GP)', 'Concentration, up to 1 minute', true, false, '{"Psion"}', 'You briefly transform into a psionic spirit. You gain the following benefits until the spell ends. Ghostly Form: You have Immunity to Poison and Psychic damage, and you have Immunity to the Exhaustion condition. Incorporeal Movement: You have a Fly Speed of 60 feet and can hover. You can move through occupied spaces as if they were Difficult Terrain. If you end your turn in such a space, you take 1d10 Force damage. If the spell ends in such a space, you are returned to the last unoccupied space you were in. Psionic Recharge: As a Magic action, you can touch a creature (which can be yourself) and roll 1d6. The creature regains one expended spell slot, the level of which equals half the number rolled (round up) or lower. Once a creature regains a spell slot from this spell, that creature can''t do so again until it finishes a Long Rest.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('power-word-fortify', 'Power Word Fortify', NULL, 'srd', 'private', 7, 'Enchantment', '1 action', '60 feet', 'V', 'Instantaneous', false, false, '{"Bard","Cleric","Psion"}', 'You fortify up to six creatures you can see within range. The spell bestows 120 Temporary Hit Points, which you divide among the spell''s recipients.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('abi-dalzims-horrid-wilting', 'Abi-Dalzim''s Horrid Wilting', NULL, 'srd', 'private', 8, 'Necromancy', '1 action', '150 feet', 'V, S, M (a bit of sponge)', 'Instantaneous', false, false, '{"Sorcerer","Wizard"}', 'You draw the moisture from every creature in a 30-foot Cube centered on a point within range. Each creature in that area makes a Constitution saving throw, taking 12d8 Necrotic damage on a failed save or half as much damage on a successful one. Constructs automatically succeed at the save, and Plant creatures automatically fail the save. Nonmagical plants in the area that aren''t creatures, such as trees and shrubs, wither and die instantly.', NULL, 'CON', NULL, NULL, 'Necrotic', '{"8":"12d8","9":"12d8"}'::jsonb, NULL, NULL, NULL, '{"type":"cube","size":30}'::jsonb),
('befuddlement', 'Befuddlement', NULL, 'srd', 'private', 8, 'Enchantment', '1 action', '150 feet', 'V, S', 'Instantaneous', false, false, '{"Bard","Druid","Sorcerer","Warlock","Wizard","Psion"}', 'You blast the mind of one creature you can see within range with psychic energy, permanently wiping away its mind and intellect. The target must make an Intelligence saving throw, taking 10d12 Psychic damage on a failed save or half as much damage on a successful one. If the failed save reduces the target to 0 Hit Points, the target''s mind is wiped clean — it has the Stunned condition for 1 hour, after which the target''s Intelligence and Charisma scores both become 1, and it loses the ability to cast spells, understand language, or communicate intelligibly. The target can be restored only by a Greater Restoration, Heal, or Wish spell.', NULL, 'INT', NULL, NULL, 'Psychic', '{"8":"10d12","9":"10d12"}'::jsonb, NULL, NULL, NULL, NULL),
('telepathy', 'Telepathy', NULL, 'srd', 'private', 8, 'Divination', '1 action', 'Unlimited', 'V, S, M (a pair of linked silver rings)', '24 hours', false, false, '{"Wizard","Psion"}', 'You create a telepathic link between yourself and a willing creature with which you are familiar. The creature can be anywhere on the same plane of existence as you. The spell ends if you or the target are no longer on the same plane. Until the spell ends, you and the target can instantaneously share words, images, sounds, and other sensory messages with each other through the link, and the target recognizes you as the creature it is communicating with. The spell enables a creature with an Intelligence score of at least 1 to understand the meaning of your words and take in the scope of any sensory messages you send to it.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('power-word-heal', 'Power Word Heal', NULL, 'srd', 'private', 9, 'Enchantment', '1 action', '60 feet', 'V', 'Instantaneous', false, false, '{"Bard","Cleric","Psion"}', 'A wave of healing energy washes over one creature you can see within range. The target regains all its Hit Points. If the creature has the Charmed, Frightened, Paralyzed, Poisoned, or Stunned condition, the condition ends. If the creature has the Prone condition, it can use its Reaction to stand up.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('psychic-scream', 'Psychic Scream', NULL, 'ua', 'private', 9, 'Enchantment', '1 action', '90 feet', 'S', 'Instantaneous', false, false, '{"Bard","Psion","Sorcerer","Warlock"}', 'You unleash the power of your mind to blast the intellect of up to ten creatures of your choice that you can see within range. Creatures that have an Intelligence score of 2 or lower are unaffected. Each target must make an Intelligence saving throw. On a failed save, the target takes 14d6 Psychic damage and has the Stunned condition. On a successful save, the target takes half as much damage only. If the target is reduced to 0 Hit Points by this damage, its head explodes if it has one. At the end of each of its turns, the Stunned target repeats the save, ending the condition on itself on a success.', NULL, 'INT', NULL, NULL, 'Psychic', '{"9":"14d6"}'::jsonb, NULL, NULL, NULL, NULL)
ON CONFLICT (id) DO NOTHING;
